name: Deploy Next.js App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > $TEMP
          ssh -i $TEMP ubuntu@ec2-18-206-171-72.compute-1.amazonaws.com 'bash -s' < scripts/deploy.sh
          